import type { Metadata } from 'next'
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import { Inter } from 'next/font/google'
import './globals.css'
import NextUi from '@/components/Providers/NextUi'
import MainNavbar from '@/components/Global/Layout/Navbar'
import TopHeader from '@/components/Global/Layout/TopHeader'
import Footer from '@/components/Global/Layout/Footer';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextUi>
          <TopHeader/>
          <MainNavbar/>
        {children}
        <Footer/>
        </NextUi>
      </body>
    </html>
  )
}
