export const cities = [
  { value: "Riyadh", enLabel: "Riyadh", arLabel: "الرياض" },
  { value: "Jeddah", enLabel: "Jeddah", arLabel: "جدة" },
  { value: "Mecca", enLabel: "Mecca", arLabel: "مكة المكرمة" },
  { value: "Medina", enLabel: "Medina", arLabel: "المدينة المنورة" },
  { value: "Dammam", enLabel: "Dammam", arLabel: "الدمام" },
  { value: "Al Khobar", enLabel: "Al Khobar", arLabel: "الخبر" },
  { value: "Jubail", enLabel: "Jubail", arLabel: "الجبيل" },
  { value: "Ta'if", enLabel: "Ta'if", arLabel: "الطائف" },
  { value: "Buraydah", enLabel: "Buraydah", arLabel: "بريدة" },
  { value: "Al Hofuf", enLabel: "Al Hofuf", arLabel: "الهفوف" },
  { value: "Qatif", enLabel: "Qatif", arLabel: "القطيف" },
  { value: "Yanbu", enLabel: "Yanbu", arLabel: "ينبع" },
  { value: "Dhahran", enLabel: "Dhahran", arLabel: "الظهران" },
  { value: "Hail", enLabel: "Hail", arLabel: "حائل" },
  { value: "Najran", enLabel: "Najran", arLabel: "نجران" },
  { value: "Tabuk", enLabel: "Tabuk", arLabel: "تبوك" },
  { value: "Abha", enLabel: "Abha", arLabel: "أبها" },
  { value: "Khamis Mushait", enLabel: "Khamis Mushait", arLabel: "خميس مشيط" },
  { value: "Jazan", enLabel: "Jazan", arLabel: "جازان" },
  { value: "Al Bahah", enLabel: "Al Bahah", arLabel: "الباحة" },
  { value: "Sakaka", enLabel: "Sakaka", arLabel: "سكاكا" },
  { value: "Arar", enLabel: "Arar", arLabel: "عرعر" },
  { value: "Rafha", enLabel: "Rafha", arLabel: "رفحاء" },
  { value: "Al Qurayyat", enLabel: "Al Qurayyat", arLabel: "القريات" },
  { value: "Al Qunfudhah", enLabel: "Al Qunfudhah", arLabel: "القنفذة" },
  { value: "Bisha", enLabel: "Bisha", arLabel: "بيشة" },
  { value: "Saihat", enLabel: "Saihat", arLabel: "سيهات" },
  { value: "Sharurah", enLabel: "Sharurah", arLabel: "شرورة" },
  { value: "Tarout", enLabel: "Tarout", arLabel: "تاروت" },
  {
    value: "Hotat Bani Tamim",
    enLabel: "Hotat Bani Tamim",
    arLabel: "حوطة بني تميم",
  },
];
